### ISSUE TITLE
Hoodies.

### ISSUE THREAD

**Issue by nelsonic** [dwyl/print-me#17]
Its time. :clock10:

**Comment by nelsonic** [comment]
<img width="589" alt="epona-website-down" src="https://cloud.githubusercontent.com/assets/194400/10198666/e8c242e8-6794-11e5-8859-4bbdbd90c8ed.png">
#**fail**

**Comment by nelsonic** [comment]
Such a shame this is Gildan ... https://www.shirtworks.co.uk/products/gildan-ladies-heavy-blend-vintage-zip-hooded-sweatshirt-gd81/
<img width="695" alt="gildan-two-tone-hoodie" src="https://cloud.githubusercontent.com/assets/194400/10198734/347c68a8-6795-11e5-9e6c-21b2cbe4e587.png">

But _something_ like this would be **_amaze**_!

**Comment by nelsonic** [comment]
This could work: https://www.cottonroots.co.uk/product/245/268/womens_vintage_full_zip_hoodie
<img width="941" alt="cotton-roots-hoodie" src="https://cloud.githubusercontent.com/assets/194400/10198782/7aea708c-6795-11e5-936d-c47bad70e830.png">

**Comment by iteles** [comment]
Just found what fairtradewear would have turned into: http://amcustomclothing.co.uk/about/ (also a good source of ethical hoodies).

Emailed them for a quote and also spoken to Epona :+1:

**Comment by nelsonic** [comment]
"would have" indeed ...

**Comment by iteles** [comment]
Finding ethical **hoodies** has actually proved quite difficult.

## Bella & Canvas [hoodies](http://www.bellacanvas.com/product/3739/unisex-zip-up-fleece-hoodie.html)

Our [t-shirts](https://github.com/dwyl/print-me#t-shirts) are of this brand and they are certainly the best bang for our buck at [£15.60 each]( (without prints) but unfortunately the [reviews for them aren't great](http://www.amazon.com/Canvas-unisex-Poly-Cotton-Fleece-Full-Zip/dp/B00KNWXOLM) - they seem to get old really quickly in the wash.  
A shame because the guys who printed our t-shirts were great and these are the only ethical hoodies they provide.

## AM Custom Clothing [hoodies](http://amcustomclothing.co.uk/shop/a-m-organic/womens-organic-zipped-hoodie/)

<img width="333" alt="screen shot 2015-10-13 at 16 09 39" src="https://cloud.githubusercontent.com/assets/4185328/10459885/b226cde6-71c9-11e5-8049-8e360e9fc794.png">
AM Custom Clothing have a **minimum order of 25 for screen printing** but do offer _Direct to Garment (DTG) printing_\* for smaller orders. These prints end up looking washed out after the first wash however.

They have both [ladies](http://amcustomclothing.co.uk/shop/a-m-organic/womens-organic-zipped-hoodie/) and [mens](http://amcustomclothing.co.uk/shop/a-m-organic/mens-organic-zipped-hoodie/) organic fair wear zip hoodies.

<img width="986" alt="AM-custom-clothing-prices" src="https://cloud.githubusercontent.com/assets/4185328/10459984/29ef5730-71ca-11e5-8c1a-6fce9b29d4a9.png">

## Epona Clothing

All [Epona **unisex**hoodies](http://www.eponashop.com/collections/men/products/zip-hoodie-khaki) are fairtrade cotton and they use only factories recommended by the Fairtrade Foundation.

<img width="640" alt="screen shot 2015-10-13 at 16 32 49" src="https://cloud.githubusercontent.com/assets/4185328/10464994/8846931a-71e4-11e5-82c9-f27054fc47c1.png">

_Awaiting final screen printing quote_. Hoodies cost £13.50 each + VAT, plus delivery of £10 per box of 20 hoodies.

**Comment by nelsonic** [comment]
Ok. great work requesting the quotes! but _how_ can we **_MVP**_ this...? 
What's the _lowest_ possible price we can pay to _trial_ this?
I don't _mind_ spending (_investing_?) the **£712.36** ... but do we _have_ to?

**Comment by nelsonic** [comment]
What if we could _retrofit_ all our _existing_ hoodies to with some **_dwyl**_  ...? :heart: :white_check_mark:

**Comment by nelsonic** [comment]
This is what _eye_ was thinking... http://www.thestudio.com/
<img width="964" alt="the-studio-custom-patches" src="https://cloud.githubusercontent.com/assets/194400/10477491/7d6beb74-724e-11e5-9b0b-66e5f62e1c7a.png">
<img width="798" alt="custom-patches-quote" src="https://cloud.githubusercontent.com/assets/194400/10477497/806111a6-724e-11e5-9752-04dd4cd7ef07.png">

We each have a handful of Organic Hoodies... we could sew/iron on the patch at a _fraction_ of the cost of getting (_the minimum order of_) _new hoodies_...

**Comment by iteles** [comment]
:+1: Actually I have exactly 2 hoodies, but that sounds like a good plan - we really don't _need_ hoodies at this stage.

3 inches seems a little small?

Are you on getting this sorted or am I?

**Comment by nelsonic** [comment]
3 inches is bigger than our current Hex stickers, but you decide what is a reasonable size.
I think we should go with the Hex (_with white border_)
You're getting it sorted because you _like_ doing this kind of thing...
Given the numbers I think it makes sense to get 100 pieced printed. 
I don't know how many people will make the _effort_ to sew them on themselves...
But we _could_ do a session at a a dwyl dinner (_for people who_ **_want**_ _to work with us_) where Natalia organises to bring sewing needles, thread & thimbles and each person brings their favourite hoodie...

I've forwarded you the email. thanks for organising it. :+1:

**Comment by iteles** [comment]
I think we should test it but I can't think of many people who would want to sew patches onto _existing_ pieces of clothing. Especially none of the women. 

I'm not convinced that the patches will actually make it onto any items of clothing, most of them will get lost in the ether. We should ask Dias what the motivation behind the LXJS ones was. Having said that, the difference between ordering 10 and ordering 100 is just ridiculously small so we might as well.

**Comment by nelsonic** [comment]
Ah... you see, you're thinking about it from the "_wrong_" angle...
What if we start a _Trend_ whereby everything you learn you get an actual _physical_ badge (_in this case_ **_patch**_) ...?

![uniform with badges](http://www.9thmuswellhill.co.uk/wp-content/uploads/2010/08/scout-uniform-badges-large.png)

So that you can recognise someone with a certain skill set from a mile away...
Sure, people might not want to add them to their existing hoodie.
But... we could pick an ethical hoodie which we could source _single units_ of and give one to each person that joins dwyl. either we could sew on the patch or they can do it themselves. but we should make a _ritual_ of it...

**Comment by nelsonic** [comment]
Its _clear_ from your _silence_ that you aren't keen on the Sew-on-Patches idea...
Do you have an alternative suggestion that will get us a Warm Wearable by the end of this month...? 
( #**_HardDeadline**_ )

**Comment by iteles** [comment]
This is our fastest route to something wearable.

The only reason I haven't ordered them yet is because when I went to place the order on Friday (3 days ago), I realised The Studio is based in California, so I emailed them to check that even with a rush order it would make it **to the UK** on time.
I also got quotes from 4 other UK-based companies (https://www.madebycooper.co.uk , embroidered-patches.co.uk, patchdepot.co.uk, aspinline.co.uk).

Today I was waiting for California to wake up (it's 10am there now as I type this) to call so I could get an answer. They can get them here _just_ whereas the UK ones doubled the order charges to get them to us by the 30th October.

@nelsonic  Do you want to change the colour or can I place the order?

**Comment by nelsonic** [comment]
This is still _alpha_. 
You like teal...
Lets just get them done.

**Comment by nelsonic** [comment]
@iteles do we have budget to re-vive this project? :heavy_dollar_sign: 
who do you _trust_ to take on the task of organising printing Hoodies for everyone in dwyl...? :question:

**Comment by iteles** [comment]
We decided at the last minute to _not_ go with patches as all simulations of this pointed to them not looking great.
We ended up with a homemade alpha ones, recycling hoodies we already owned for #websummit in November 2015 which turned out pretty cool!

![img_6459](https://cloud.githubusercontent.com/assets/4185328/14229853/92b1cc76-f938-11e5-8b03-899bcc2493c8.jpg)
![img_6460](https://cloud.githubusercontent.com/assets/4185328/14229851/92af99b0-f938-11e5-8f9e-6252038ba0c8.jpg)
![img_6461](https://cloud.githubusercontent.com/assets/4185328/14229854/92b1f570-f938-11e5-8f38-e5e33d7073be.jpg)
![img_6463](https://cloud.githubusercontent.com/assets/4185328/14229852/92b1a21e-f938-11e5-8821-4f28a04e6744.jpg)
![img_6454](https://cloud.githubusercontent.com/assets/4185328/14229858/c0cdbc96-f938-11e5-8772-6aabefb3121c.jpg)
<img width="294" alt="screen shot 2016-04-03 at 01 10 22" src="https://cloud.githubusercontent.com/assets/4185328/14229859/e59102cc-f938-11e5-87b2-8122ec62207b.png">

**Comment by iteles** [comment]
I'll be going through the accounts and we can define priorities mid-April at the latest.

**Comment by ghost** [comment]
@iteles ok to close?

**Comment by iteles** [comment]
I haven't even updated this with the hoodies we *actually* got printed yet. It has to stay open until the info is captured 👍

**Comment by nelsonic** [comment]
Once the info is captured about the hoodies that _did_ get printed 
including the colors, softness vs. durability and price
we need to get people's sizes and do a print run ASAP!

**Comment by sohilpandya** [comment]
As much as I ❤️  the green hoodie that I've got, I'd like to ask if we can consider these ones. 

http://shoparos.com/mens/relaxed-fit-zip-up-jacket

It'd be great to have a nap every now and then 😉  😆  🤣

**Comment by nelsonic** [comment]
@sohilpandya that is a _sweet_ hoodie! 😍 
I think Hoodies (_and other "merch"_) is delayed till https://github.com/dwyl/hq/issues/118 is done... 😉 
How is your Green Hoodie holding up? 💭

**Comment by sohilpandya** [comment]
Well, dwyl/hq#118 is done! Unbelievable!!! 🎉 

My hoodie is really good! but I feel it's a summer wear of sorts and not been able to wear it as much as I'd like to have. 

I'm also a fleece guy so a fleece or a zip up jacket would mean that I can literally wear dwyl clothing all the times! I mean I'm always wearing a dwyl Tee 😉

**Comment by iteles** [comment]
Winter is coming! (I know, so may possible gifs)
Time to revisit for some warmer hoodies?

**Comment by rub1e** [comment]
Winter is here. Storm Caroline is bringing snow, and forcing poor Scottish children to miss school. I personally am somewhat chilly.

I will get quotes from the following ethical hoodies merchants, please add to the list if you have any bright ideas folks (or if you know them to be untrustworthy scoundrels):

* http://www.pier32.co.uk/our-ethics/
* http://amcustomclothing.co.uk/
* https://www.shirtworks.co.uk/about/our-ethics
* https://www.cottonroots.co.uk/information/what_we_do/cotton_roots
* https://rapanuiclothing.com/sustainability/

It looks like warmer/heavier hoodies have a weight of 250gsm minimum, but if anyone is a a textile expert please let me know

**Comment by iteles** [comment]
@rub1e Thanks for these!

Our t-shirts were [Bella & Canvas](https://www.firelabel.co.uk/hoodies-and-sweats/mens/zip-up-hoodies-and-sweats/cv3739-canvas-unisex-full-zip-hoodie.html) and I actually have one of [these hoodies](https://www.firelabel.co.uk/hoodies-and-sweats/mens/zip-up-hoodies-and-sweats/cv3909-canvas-unisex-full-zip-hoodie.html) which is warmer than the average hoodie (supports your theory of 250gsm min), but find that sadly they all get lint-y really quickly 😭 

The one thing I'll say is people quite like the dangly white chords in https://www.firelabel.co.uk/hoodies-and-sweats/mens/zip-up-hoodies-and-sweats/cv3909-canvas-unisex-full-zip-hoodie.html - not for the white-ness but for the fact that they are all rope and don't have the usual plastic shoelace ends (_obviously_ nowhere near a requirement, but _ceteris paribus_, we'd go for that).

**Comment by nelsonic** [comment]
@iteles I _love_ Hoodies. 
Sadly, my light blue hoodie has lasted fewer than 12 months 
and I've only used it about 30 times before it got very "lint-y"

There could be a `case` for getting Embroidered "fleeces" 
as they tend to be more durable (_don't get "lint-y"_) 
and are designed to be warm and machine washable.
 (_my hoodies have faded badly from washing_)

"Shirt Works" does them: https://www.shirtworks.co.uk/products/outdoor-fleece/full-zip-styles/
https://www.shirtworks.co.uk/products/sol-nova-micro-fleece-jacket-10586/
![image](https://user-images.githubusercontent.com/194400/33764713-894dfeb6-dc0d-11e7-8ecb-288b61ebe5a6.png)

The design is "_boring_", but it should last longer than the average hoodie.

This one is a bit nicer:
https://www.shirtworks.co.uk/products/sol-turbo-pro-knitted-fleece-jacket-01652/
![image](https://user-images.githubusercontent.com/194400/33764667-52a282c4-dc0d-11e7-8562-0bc08b803132.png)
(_ignore the "Turbo Pro" naming BS_)

**Comment by rub1e** [comment]
> (ignore the "Turbo Pro" naming BS)

@nelsonic I know, right! I mean, at best you're an *average-speed intermediate* :wink:

Safe, on the list - will enquire about embroidery vs printing too. Loving the 340gsm :fire: 

@iteles I believe these are referred to as *Contrast Zoodies* :confused: I happen to currently be wearing one, and yes, they're ace :smile:

**Comment by sohilpandya** [comment]
I'm 100% pro fleece. They are the best. 😊

**Comment by rub1e** [comment]
Many hoodies, zoodies, hoodoo, voodoo, and fleeces have been inquired about. So, so many. I'll collate the best candidates and find a sensible way to display them all when I've had the quotes back.

(The only one I left out was rapanui clothing cos they were silly money)

**Comment by rub1e** [comment]
Some cracking contenders in here, more to follow pending a couple of replies (like one of them tried to sell us Micro-fleeces and I'm like it's chunky or it's nothing.)

[Doc](https://docs.google.com/presentation/d/16W3ipNWDo9gxxOHuEccFE8hsGG86Je-OEx4nGsVUBiE/edit?usp=sharing)

**Comment by nelsonic** [comment]
Of the hoodies, Prefer the _Certified_ Fairtrade hoodie. http://amcustomclothing.co.uk/shop/a-m-fairtrade-clothing/mens-fairtrade-zip-hoodie
![image](https://user-images.githubusercontent.com/194400/34680129-087b872c-f490-11e7-843e-70183b50bea1.png)

Still keen on Fleece ... for the reasons outlined above. ⬆️ 
The Pier 32 Fleece http://www.pier32.co.uk/product/sw700-fleece-jacket/ 
_appears_ to have a **50 items** _minimum order_ ...
![image](https://user-images.githubusercontent.com/194400/34681160-dc16cdd8-f492-11e7-816b-ec6661417ce2.png)
were you able to _confirm_ this with them? 50 feels like a lot ... 🤔 
However given that these are _cheaper_ we it could end up being a similar total cost. 💭

**Comment by iteles** [comment]
@rub1e 🎉 I would also be keen on the AM Clothing hoodies (either or, not sure whether air miles or fair miles win out yet). Would they be happy to sell and ship us a single hoody so we can check quality and have samples for when people make their order?

(I'm not a fan of fleeces, but happy to have a small number of them made if they're not exorbitant)

**Comment by rub1e** [comment]
OK so why don't I request a sample of both the Hoodies and the Fleeces mentioned above so we can take a more informed view - and then we can get them ordered! (I'll also inquire about minimum runs)

**Comment by iteles** [comment]
@rub1e Yes please! I don't mind paying for the samples if we get to use them later. Make L hoodies in red for example.

**Comment by rub1e** [comment]
I've asked for samples BTW, just waiting to hear back about that and minimum runs. 

Question @iteles: 

> Make L hoodies in red for example.

Is the L "large" or "Ladies"?

**Comment by nelsonic** [comment]
@rub1e, L = "_Men's **Large**_". 😉  (_good to seek clarification_) 👍

**Comment by iteles** [comment]
Make = male 🙄  #typo

**Comment by iteles** [comment]
Sample (no printing) hoody and fleece have now been ordered, thanks @rub1e .

@nelsonic @sohilpandya Fleece is already at Focus Hub if you want to come and take a look.

**Comment by rub1e** [comment]
If anyone is following this thread but not on gitter, here is the spreadsheet with size/colour options - please fill it in asap!

(For colours, please tick the ones you're WILLING to have and we'll narrow it down from there)

https://docs.google.com/spreadsheets/d/1p1ufSyfZ_koFsqCr7SvJOrvyIV0f3crrArw7gWeOZps/edit#gid=0

**Comment by rub1e** [comment]
The files for the branding are saved in the `dwyl drive > marketing` - the ones marked `FINAL` are editable so can be used in the future, and the ones marked `FINAL-outline` have the text converted to outlines so that the font doesn't change, and therefore aren't editable.

That's right, I'm a graphic designer now.

**Comment by rub1e** [comment]
UPDATE: having received very disappointing fleece and hoodie samples from AMC, we've requested a sample of the [Chunky Hoodie](https://www.shirtworks.co.uk/products/awdis-chunky-zoodie-jh052/) which will be delivered on Friday

**Comment by rub1e** [comment]
The chunky hoodies are winners: robust but soft, casual but fierce. They remind me of a young me. 

We've also narrowed down the colour options, so please revisit [the spreadsheet](https://docs.google.com/spreadsheets/d/1p1ufSyfZ_koFsqCr7SvJOrvyIV0f3crrArw7gWeOZps/edit#gid=0) and repick a colour.

Quick note on sizes - I've tried on the Large and it's a good fit even for me. Given that I'm by far the largest and funniest dwyler, I humbly suggest that the XL size shouldn't be needed

EDIT - **please only pick one colour** - this is the final choice before we order, not as before when we were trying to narrow down the colours

**Comment by rub1e** [comment]
UPDATE: After much ado, followed by even more ado, our order is finally being processed. 

Because of the outrageous service we've received, we don't 100% trust `Shirtworks` so we're requesting to see the first batch from the print run before we approve the rest - just to be on the safe side

So I'll update this with the ETA when that's been approved

**Comment by rub1e** [comment]
And yet more ado: the mockup we were sent says:

> This mockup is representational only and does not show true scale or relationship between objects

Perhaps controversially, this is information we need before we can sign the order off. So I've sent it back to them asking for a proper mockup, will update

**Comment by rub1e** [comment]
UPDATE: we've approved the mockups so we're just waiting for the results of the first print run so we can double check that it's exactly as we want it - expected on Monday 9th

**Comment by rub1e** [comment]
The hoodies arrived a little while ago

Is there anyone who requested a hoodie but hasn't yet received it?

(I'll close this issue shortly and chase people on gitter)

**Comment by rub1e** [comment]
Closing because we have our hoodies, and they are awesome 💟

**Comment by iteles** [comment]
@rub1e Please add to the readme, including a little historical context from https://github.com/dwyl/print-me/issues/17#issuecomment-204831906 ;)

It would be good to have all the steps so that next time we know exactly:
a) What to expect, and 
b) What to watch out for (like the conversations we had on the positioning of the logo, etc)

**Comment by rub1e** [comment]
## What to think about first

**Hoodies or fleeces?** We did look at fleeces, but we didn't find any we particularly liked - they all have a quite cheap look & feel. It's safe to say that hoodies are what most people like. (That said, it's on my list to investigate and find a source of decent fleeces.)

**Weight / gsm** Weights are measured in grams per square metre, and we found that anything below 250 gsm feels flimsy. (I personally think that a significant amount of polyester is uncomfortable - go for cotton if possible).

**Colours** Most places let you do a mix of colours and sizes at no extra cost, but unfortunately purple isn't allowed. 

## Printing

We went with the dwyl logo in white with `dwyl` in white underneath on the left breast (front), 6cm wide:

![screenshot 2018-06-26 at 13 21 30](https://user-images.githubusercontent.com/11595920/41911203-eef00a92-7943-11e8-8a90-30e9b1261cea.png)

And on the back a dwyl logo in white with `dwyl.com` next to it, 21cm wide:

![screenshot 2018-06-26 at 13 23 39](https://user-images.githubusercontent.com/11595920/41912213-eee2da90-7946-11e8-805a-e7768378f408.png)

As for positioning... 

The printing on the back needs to be low enough that it isn't obscured when the hood hangs down - ask the printer to confirm this.

The printing on the front you'll have to look at yourself - the distance to the zip changes depending on the size of the garment. Best thing is to get a sample and look at it yourself, and make sure the printers send you a mockup and ideally a single garment from the initial run so you can check before you give final signoff.

## Files

The files for the branding are saved in the `dwyl drive > marketing` - the ones marked `FINAL` are editable so can be used in the future, and the ones marked `FINAL-outline` have the text converted to outlines so that the font doesn't change, and therefore aren't editable.
